<a href="https://colab.research.google.com/github/PradeepKumarM30/MLWithLargeData/blob/main/20MAI0030FAT.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#Load Imports
import numpy as np

In [2]:
#Load Files - This file was created in local machine with some random inputs and not taken from any online dataset
file = np.loadtxt(open("/content/sample_data/data.csv", "rb"), delimiter=",", skiprows=1) 

In [3]:
#Visualising the data 
file

array([[-1., -1.,  0.],
       [-1.,  1.,  1.],
       [ 1., -1.,  1.],
       [ 1.,  1.,  1.]])

In [4]:
#converting rows and columns to each other for vectorisation that will happen later in this code
new_file = file.T

In [5]:
#Now the new file looks like
print(new_file)

[[-1. -1.  1.  1.]
 [-1.  1. -1.  1.]
 [ 0.  1.  1.  1.]]


In [6]:
#Assign train values 
X_train,Y_train = new_file[0:2,:],new_file[2,:] #take the input data from file 

In [7]:
#input snapshot
print(X_train,' ',Y_train)

[[-1. -1.  1.  1.]
 [-1.  1. -1.  1.]]   [0. 1. 1. 1.]


In [26]:
print(X_train[:,0])

[-1. -1.]


In [8]:
#initialise weight and bias matrix
def initialize_with_zeros(dim):
   
    w = np.zeros((dim,1))
    b = 0
   
    assert(w.shape == (dim, 1))
    assert(isinstance(b, float) or isinstance(b, int))
    
    return w, b

In [9]:
#Sigmoid activation utility
def sigmoid(z):
   
    s = 1/(1+(np.exp(-z)))
    
    return s

In [10]:
def binary_activation(z):
  s = np.zeros(z.shape)
  rows = z.shape[0]
  cols = z.shape[1]
  for x in range(0, rows):
    for y in range(0, cols):
         if z[x,y]  >= 0.2: 
           s[x,y] = 1
         else :
           s[x,y] = 0
  return s

In [11]:
#forward propogation
def propagate(w, b, X, Y):
    
    m = X.shape[1]
    
    A = binary_activation(np.dot(w.T,X)+b)                                   
    cost = (-1/m) * (np.dot(Y,(np.log(A)).T) + np.dot(1-Y,(np.log(1-A)).T))                               
    dw = np.dot(X,(A-Y).T)/m
    db = (1/m) * np.sum(A-Y)

    assert(dw.shape == w.shape)
    assert(db.dtype == float)
    cost = np.squeeze(cost)
    assert(cost.shape == ())
    
    grads = {"dw": dw,
             "db": db}
    
    return grads, cost

In [105]:
#doing the computations
def optimize(w, b, X, Y, num_iterations, learning_rate, print_cost = False):
    
    costs = []
    
    for i in range(num_iterations):
      for row in range(0,X.shape[1]):
        grads, cost = propagate(w,b,X[:,row:row+1],Y[row])

        print(X.shape)

        print("Printing x1: ",X[:,0:1]," Printing Y: ",Y[0],"  ")
        print("Printing x1: ",X[:,1:2]," Printing Y: ",Y[1],"  ")
        print("Printing x1: ",X[:,2:3]," Printing Y: ",Y[2],"  ")
        print("Printing x1: ",X[:,3:4]," Printing Y: ",Y[3],"  ")
        
        dw = grads["dw"]
        db = grads["db"]
        
        w = w - (learning_rate * dw)
        b = b - (learning_rate * db)
        
        if i % 100 == 0:
            costs.append(cost)
        
        if print_cost and i % 10 == 0:
            print ("Cost after iteration %i: %f" %(i, cost))
    
    
    params = {"w": w,
              "b": b}
    
    grads = {"dw": dw,
             "db": db}
    
    return params, grads, costs

In [106]:
#Perceptron driver code
def perceptron(X_train, Y_train, num_iterations, learning_rate = 0.5):
   
    w,b = initialize_with_zeros(X_train.shape[0])

    parameters, grads, costs = optimize(w, b, X_train, Y_train, num_iterations, learning_rate)
    
    w = parameters["w"]
    b = parameters["b"]
    
#    Y_prediction_test = predict(w, b, X_test)
    Y_prediction_train = predict(w, b, X_train)

    print("train accuracy: {} %".format(100 - np.mean(np.abs(Y_prediction_train - Y_train)) * 100))
#    print("test accuracy: {} %".format(100 - np.mean(np.abs(Y_prediction_test - Y_test)) * 100))

    
    d = {"costs": costs, 
         "Y_prediction_train" : Y_prediction_train, 
         "w" : w, 
         "b" : b,
         "learning_rate" : learning_rate,
         "num_iterations": num_iterations}
    
    return d

In [107]:
#function to predict models performance
def predict(w, b, X):
    
    m = X.shape[1]
    Y_prediction = np.zeros((1,m))
    w = w.reshape(X.shape[0], 1)
    
    A = binary_activation(np.dot(w.T,X)+b)
    
    for i in range(A.shape[1]):
        Y_prediction[:,i] = 1 if A[:,i] > 0.52 else 0
    
    assert(Y_prediction.shape == (1, m))
    
    return Y_prediction

In [108]:
#the main driver code
print(" M PRADEEP KUMAR - 20MAI0030")
output_dict = perceptron(X_train,Y_train,2,1)
print(output_dict)

 M PRADEEP KUMAR - 20MAI0030
(2, 4)
Printing x1:  [[-1.]
 [-1.]]  Printing Y:  0.0   
Printing x1:  [[-1.]
 [ 1.]]  Printing Y:  1.0   
Printing x1:  [[ 1.]
 [-1.]]  Printing Y:  1.0   
Printing x1:  [[1.]
 [1.]]  Printing Y:  1.0   
(2, 4)
Printing x1:  [[-1.]
 [-1.]]  Printing Y:  0.0   
Printing x1:  [[-1.]
 [ 1.]]  Printing Y:  1.0   
Printing x1:  [[ 1.]
 [-1.]]  Printing Y:  1.0   
Printing x1:  [[1.]
 [1.]]  Printing Y:  1.0   
(2, 4)
Printing x1:  [[-1.]
 [-1.]]  Printing Y:  0.0   
Printing x1:  [[-1.]
 [ 1.]]  Printing Y:  1.0   
Printing x1:  [[ 1.]
 [-1.]]  Printing Y:  1.0   
Printing x1:  [[1.]
 [1.]]  Printing Y:  1.0   
(2, 4)
Printing x1:  [[-1.]
 [-1.]]  Printing Y:  0.0   
Printing x1:  [[-1.]
 [ 1.]]  Printing Y:  1.0   
Printing x1:  [[ 1.]
 [-1.]]  Printing Y:  1.0   
Printing x1:  [[1.]
 [1.]]  Printing Y:  1.0   
(2, 4)
Printing x1:  [[-1.]
 [-1.]]  Printing Y:  0.0   
Printing x1:  [[-1.]
 [ 1.]]  Printing Y:  1.0   
Printing x1:  [[ 1.]
 [-1.]]  Printing Y:  1

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:7: RuntimeWarning: divide by zero encountered in log
  import sys
